name: CI
on: [pull_request]
jobs:
  test-skip-install-and-use-bundler:
    name: runner / erb_lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/using_gemfile
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/test/gemfile/Gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: install erb_lint with version written in Gemfile.lock
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          brakeman_version: 'gemfile'
      - run: |
          test "$(bundle exec erb_lint --version)" == "erb_lint 0.4.0"
